### ISSUE TITLE
Delta Messages

### ISSUE THREAD

**Issue by taggie05** [AzureAfloat/signalk-iothub-plugin#2]
Create functionality to allow each device's delta messages to be sent to its corresponding device when registered through the plugin.

**Comment by codefoster** [comment]
Like we started working on, this involves creating an array of IoT Hub SDK clients. I think we want to hold them in a dictionary keyed on the device name. If the client for a given device already exists, we want to use it because we don't want to keep creating them. They're pretty expensive in terms of memory. I don't remember how far we got on it though.

**Comment by codefoster** [comment]
because we allow the user to configure connection strings, this is no longer necessary
